Update build script

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -1,70 +1,82 @@
 name: CI Build
 on:
   push:
-    branches: ["main"]
-  pull_request:
+    branches: [main]
 
+  pull_request: null
+  workflow_dispatch: null
 jobs:
   build:
     runs-on: ubuntu-latest
     defaults:
-      run:
-        shell: "bash"
+      run: { shell: bash }
     environment: aws
-    permissions:
-      contents: read
-      checks: write # Allow scacap/action-surefire-report
+    permissions: { contents: read, checks: write, issues: read }
     concurrency:
-      group: ${{ github.workflow }}-${{ github.ref }}
-      cancel-in-progress: true
+      {
+        group: "${{ github.workflow }}-${{ github.ref }}",
+        cancel-in-progress: true,
+      }
+    outputs:
+      {
+        release-required: "${{ steps.check-release.outputs.release-required }}",
+      }
     steps:
       - name: Free Disk Space
+        id: free-disk-space
+        if: ${{ false }}
         run: |
           sudo rm -rf /usr/local/lib/android
           sudo rm -rf /usr/share/dotnet
       - name: Checkout the repository
+        id: checkout
         uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+        with: { fetch-depth: 0 }
       - name: Set up JDKs
+        id: setup-java
         uses: actions/setup-java@v4
         with:
-          distribution: "temurin"
+          distribution: temurin
           java-version: |
             11
             17
-          cache: "maven"
+          cache: maven
       - name: Cache SonarCloud packages
+        id: cache-sonar
         uses: actions/cache@v4
         with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: Enable testcontainer reuse
-        run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
+          {
+            path: ~/.sonar/cache,
+            key: "${{ runner.os }}-sonar",
+            restore-keys: "${{ runner.os }}-sonar",
+          }
+      - {
+          name: Enable testcontainer reuse,
+          id: enable-testcontainer-reuse,
+          run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties",
+        }
       - name: Create AWS test setup
+        id: create-aws-test-setup
         run: |
           echo "owner = \"$OWNER\"" > cloudSetup/terraform.tfvars
           echo "deputy = \"$DEPUTY\"" >> cloudSetup/terraform.tfvars
           terraform -chdir=cloudSetup/ init
           terraform -chdir=cloudSetup/ apply -auto-approve
         env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          OWNER: ${{ secrets.AWS_TAG_OWNER }}
-          DEPUTY: ${{ secrets.AWS_TAG_DEPUTY }}
+          {
+            AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}",
+            AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
+            OWNER: "${{ secrets.AWS_TAG_OWNER }}",
+            DEPUTY: "${{ secrets.AWS_TAG_DEPUTY }}",
+          }
       - name: Run tests and build with Maven
-        id: pk-verify
+        id: build-pk-verify
         run: |
           mvn --batch-mode clean verify \
               -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
               -DtrimStackTrace=false
-      - name: Publish Test Report
-        uses: scacap/action-surefire-report@v1
-        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
       - name: Sonar analysis
+        id: sonar-analysis
         if: ${{ env.SONAR_TOKEN != null }}
         run: |
           mvn --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
@@ -72,61 +84,53 @@ jobs:
               -DtrimStackTrace=false \
               -Dsonar.token=$SONAR_TOKEN
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      - name: Destroy cluster
-        run: terraform -chdir=cloudSetup/ destroy -auto-approve
-        if: always() # also run if tests failed
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-
-      - name: Verify Release Artifacts
-        run: |
-          print_message() {
-              local -r message=$1
-              echo "$message"
-              echo "$message" >> "$GITHUB_STEP_SUMMARY"
+          {
+            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
+            SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}",
           }
-
-          print_message "# Release Artifacts"
-
-          IFS=$'\n' artifacts_array=($ARTIFACTS)
-          missing_files=()
-          for file in "${artifacts_array[@]}";
-          do  
-              echo "Checking if file $file exists..."
-              if ! [[ -f "$file" ]]; then
-                  print_message "* ⚠️ \`$file\` does not exist ⚠️"
-                  echo "Content of directory $(dirname "$file"):"
-                  ls "$(dirname "$file")"
-                  missing_files+=("$file")
-              else
-                  print_message "* \`$file\` ✅" 
-              fi
-          done
-          print_message ""
-          number_of_missing_files=${#missing_files[@]}
-          if [[ $number_of_missing_files -gt 0 ]]; then
-              print_message "⚠️ $number_of_missing_files release artifact(s) missing ⚠️"
-              exit 1
-          else
-              print_message "All ${#artifacts_array[@]} artifact(s) present ✅"
-          fi
+      - name: Destroy cluster
+        id: destroy-aws-test-setup
+        run: terraform -chdir=cloudSetup/ destroy -auto-approve
+        if: always()
         env:
-          ARTIFACTS: ${{ steps.pk-verify.outputs.release-artifacts }}
-
-  # [impl->dsn~release-workflow.ci-build-starts-release~1]
+          {
+            AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}",
+            AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
+          }
+      - name: Verify Release Artifacts
+        id: verify-release-artifacts
+        run: "print_message() {\n    local -r message=$1\n    echo \"$message\"\n    echo \"$message\" >> \"$GITHUB_STEP_SUMMARY\"\n}\n\nprint_message \"### Release Artifacts\"\n\nIFS=$'\\n' artifacts_array=($ARTIFACTS)\nmissing_files=()\nfor file in \"${artifacts_array[@]}\";\ndo  \n    echo \"Checking if file $file exists...\"\n    if ! [[ -f \"$file\" ]]; then\n        print_message \"* ⚠️ \\`$file\\` does not exist ⚠️\"\n        echo \"Content of directory $(dirname \"$file\"):\"\n        ls \"$(dirname \"$file\")\"\n        missing_files+=(\"$file\")\n    else\n        print_message \"* \\`$file\\` ✅\" \n    fi\ndone\nprint_message \"\"\nnumber_of_missing_files=${#missing_files[@]}\nif [[ $number_of_missing_files -gt 0 ]]; then\n    print_message \"⚠️ $number_of_missing_files release artifact(s) missing ⚠️\"\n    exit 1\nfi\n"
+        env:
+          {
+            ARTIFACTS: "${{ steps.build-pk-verify.outputs.release-artifacts }}",
+          }
+      - name: Upload artifacts
+        id: upload-artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          {
+            name: artifacts,
+            path: "${{ steps.build-pk-verify.outputs.release-artifacts }}",
+            retention-days: 5,
+          }
+      - name: Check if release is needed
+        id: check-release
+        if: ${{ github.ref == 'refs/heads/main' }}
+        run: |
+          if mvn --batch-mode com.exasol:project-keeper-maven-plugin:verify-release --projects .; then
+              echo "### ✅ Release preconditions met, start release" >> "$GITHUB_STEP_SUMMARY"
+              echo "release-required=true" >> "$GITHUB_OUTPUT"
+          else
+              echo "### 🛑 Release precondition not met, skipping release" >> "$GITHUB_STEP_SUMMARY"
+              echo "See log output for details." >> "$GITHUB_STEP_SUMMARY"
+              echo "release-required=false" >> "$GITHUB_OUTPUT"
+          fi
+        env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
   start_release:
     needs: build
-    if: ${{ github.ref == 'refs/heads/main' }}
-    concurrency:
-      cancel-in-progress: false
-      group: "release"
+    if: ${{ github.ref == 'refs/heads/main' && needs.build.outputs.release-required == 'true' }}
+    concurrency: { cancel-in-progress: false, group: release }
     secrets: inherit
-    permissions:
-      contents: write
-      actions: read
+    permissions: { contents: write, actions: read, issues: read }
     uses: ./.github/workflows/release.yml
-    with:
-      started-from-ci: true
+    with: { started-from-ci: true }
